# Generated by Django 5.2.5 on 2025-08-20 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proyecto_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('link_repo', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='usuarios.usuario')),
            ],
        ),
    ]
