# Generated by Django 5.2.5 on 2025-08-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=300)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos/')),
            ],
        ),
    ]
