# Generated by Django 5.2.5 on 2025-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
