# Generated by Django 5.2.5 on 2025-08-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
